In [1]:
import pandas as pd # load dataset 
import seaborn as sns # generate heat map
import numpy as np
import matplotlib.pyplot as plt
tableA = pd.read_csv('6. Dataset PCA/MeterA_pca.csv', header='infer') # read MeterA csv file
tableA = tableA.drop('Class Attruibute', axis=1)
tableB = pd.read_csv('6. Dataset PCA/MeterB_pca.csv', header='infer') # read MeterB csv file
tableB = tableB.drop('Class Attruibute', axis=1)
tableC = pd.read_csv('6. Dataset PCA/MeterC_pca.csv', header='infer') # read MeterC csv file
tableC = tableC.drop('Class Attruibute', axis=1)

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
scaler = StandardScaler()
pca = PCA(n_components=4)
tableA_Scaled = scaler.fit(tableA).transform(tableA)
tableB_Scaled = scaler.fit(tableB).transform(tableB)
tableC_Scaled = scaler.fit(tableC).transform(tableC)
tableA_Scaled

array([[-1.71130694e+00,  2.09057027e+00, -1.67576501e+00,
        -6.85111410e-01,  6.06570505e-01],
       [-1.66956774e+00,  1.61781131e+00, -9.82416224e-01,
         1.43478418e+00,  3.70852307e-01],
       [-1.62782855e+00,  9.08808825e-01, -8.69529290e-01,
         1.94205421e+00, -4.89668114e-01],
       [-1.58608936e+00,  1.09490599e-01, -1.12185378e+00,
        -3.01110062e-01, -1.13884708e-01],
       [-1.54435016e+00, -2.23715480e-03, -1.11031272e+00,
        -1.17156675e+00,  8.01783456e-01],
       [-1.50261097e+00,  1.92921096e-01, -9.71798050e-01,
        -1.56052316e+00,  1.04559099e+00],
       [-1.46087177e+00,  4.94040085e-01, -8.23100420e-01,
        -8.86560675e-01,  1.43278704e+00],
       [-1.41913258e+00,  3.15925960e-01, -9.99780928e-01,
        -7.64842059e-01,  3.69842423e-01],
       [-1.37739339e+00,  8.43558932e-01, -7.87682735e-01,
        -1.39935441e+00,  1.35936295e+00],
       [-1.33565419e+00, -2.51472143e-01, -5.94819326e-01,
        -3.15403868e-01

In [3]:
tableA_covarianceMatrix = np.cov(np.transpose(np.array(tableA_Scaled)))
tableB_covarianceMatrix = np.cov(np.transpose(np.array(tableB_Scaled)))
tableC_covarianceMatrix = np.cov(np.transpose(np.array(tableC_Scaled)))

pca_tableA = pca.fit(tableA_covarianceMatrix).transform(tableA_covarianceMatrix)
pca_tableB = pca.fit(tableB_covarianceMatrix).transform(tableB_covarianceMatrix)
pca_tableC = pca.fit(tableC_covarianceMatrix).transform(tableC_covarianceMatrix)

In [4]:
df_pca_tableA = pd.DataFrame(pca_tableA, columns=['PC1','PC2','PC3','PC4'])
df_pca_tableB = pd.DataFrame(pca_tableB, columns=['PC1','PC2','PC3','PC4'])
df_pca_tableC = pd.DataFrame(pca_tableC, columns=['PC1','PC2','PC3','PC4'])

tableA_pca_vertically = df_pca_tableA['PC1'].append([df_pca_tableA['PC2'],df_pca_tableA['PC3'],df_pca_tableA['PC4']]).reset_index(drop=True)
tableB_pca_vertically = df_pca_tableB['PC1'].append([df_pca_tableB['PC2'],df_pca_tableB['PC3'],df_pca_tableA['PC4']]).reset_index(drop=True)
tableC_pca_vertically = df_pca_tableC['PC1'].append([df_pca_tableC['PC2'],df_pca_tableC['PC3'],df_pca_tableA['PC4']]).reset_index(drop=True)
print('correlation of data of tableA and tableB is {}'.format(np.corrcoef(tableA_pca_vertically,tableB_pca_vertically)[0,1]))
print('correlation of data of tableB and tableC is {}'.format(np.corrcoef(tableB_pca_vertically,tableC_pca_vertically)[0,1]))
print('correlation of data of tableA and tableC is {}'.format(np.corrcoef(tableA_pca_vertically,tableC_pca_vertically)[0,1]))

correlation of data of tableA and tableB is -0.5152834068368902
correlation of data of tableB and tableC is -0.13573605491151863
correlation of data of tableA and tableC is 0.0018912908557964304


In [5]:
print(pca_tableA)
print(pca_tableB)
print(pca_tableC)

[[-7.92699371e-01  5.28553056e-17 -3.28426904e-17  1.64979561e-01]
 [ 7.97284918e-01  6.75896361e-01 -2.28623624e-01  2.78133275e-02]
 [-7.49259001e-01  2.91160598e-01  1.87523409e-01 -1.50453691e-01]
 [ 1.47637487e-01 -5.71075608e-01 -6.63650360e-01 -4.70702301e-02]
 [ 5.97035967e-01 -3.95981351e-01  7.04750576e-01  4.73103217e-03]]
[[ 8.86200701e-01  4.93717788e-17  3.38771865e-16  1.10538325e-01]
 [-8.74769127e-01 -4.45664396e-01 -5.46346743e-01  2.24911474e-02]
 [ 8.17494676e-01 -2.39451590e-01 -1.35265489e-01 -1.07367235e-01]
 [-3.27956900e-01  8.61897833e-01 -1.49593914e-01 -1.94693028e-02]
 [-5.00969350e-01 -1.76781847e-01  8.31206146e-01 -6.19293498e-03]]
[[ 8.89732149e-01  3.15889835e-16  2.11194306e-19 -2.96597822e-01]
 [-2.03138250e-01  8.42681520e-01 -2.25449925e-01  7.91349595e-02]
 [-7.93816291e-01 -1.03244582e-01  7.00722598e-01 -7.34880138e-02]
 [ 6.85033096e-01 -2.67674402e-01  1.86745085e-01  3.08626057e-01]
 [-5.77810704e-01 -4.71762537e-01 -6.62017757e-01 -1.7675180