In [1]:
import pandas as pd # load dataset 
import seaborn as sns # generate heat map
import numpy as np
import matplotlib.pyplot as plt
tableA = pd.read_csv('5. Dataset Feature Dropping/MeterA_featureSelection.csv', header='infer') # read MeterA csv file
tableA = tableA.drop('Unnamed: 0', axis=1)
tableA = tableA.drop('Class Attruibute', axis=1)
tableB = pd.read_csv('5. Dataset Feature Dropping/MeterB_featureSelection.csv', header='infer') # read MeterB csv file
tableB = tableB.drop('Unnamed: 0', axis=1)
tableB = tableB.drop('Class Attruibute', axis=1)
tableC = pd.read_csv('5. Dataset Feature Dropping/MeterC_featureSelection.csv', header='infer') # read MeterC csv file
tableC = tableC.drop('Unnamed: 0', axis=1)
tableC = tableC.drop('Class Attruibute', axis=1)

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
scaler = StandardScaler()
pca4 = PCA(n_components=4)
pca5 = PCA(n_components=5)
tableA_Scaled = scaler.fit(tableA).transform(tableA)
tableB_Scaled = scaler.fit(tableB).transform(tableB)
tableC_Scaled = scaler.fit(tableC).transform(tableC)
tableA_Scaled

array([[ 9.61066975e-01, -5.51762461e-01, -1.82472234e+00,
         8.20842688e-01,  3.31664642e+00],
       [ 1.00279448e+00, -9.44065718e-01, -4.49788945e-01,
         1.62301423e+00,  2.06783279e+00],
       [ 9.18002910e-01, -2.30339135e-01,  3.12573796e-01,
         1.59759866e+00,  1.29911838e+00],
       [ 9.39969374e-01,  6.38158100e-01, -3.48063876e-01,
        -9.00073528e-02,  7.03297428e-01],
       [ 8.97738692e-01,  4.58710041e-01, -6.39313257e-01,
        -9.06435894e-01,  7.64734199e-01],
       [ 8.16830518e-01,  1.79974226e-01, -1.04194064e+00,
        -9.31314323e-01,  7.34728356e-01],
       [ 9.63591056e-01, -4.25745441e-01, -9.43099823e-01,
        -4.74750534e-01,  7.63306183e-01],
       [ 9.28727837e-01,  2.58338819e-01, -8.02344488e-01,
        -2.12027886e-01,  6.74719610e-01],
       [ 9.70711819e-01, -6.16911430e-01, -1.62938418e+00,
        -2.62100353e-01,  7.53304214e-01],
       [ 6.50206825e-01,  2.04492052e-01,  3.05795431e-02,
        -6.70456495e-01

In [3]:
tableA_covarianceMatrix = np.cov(np.transpose(np.array(tableA_Scaled)))
tableB_covarianceMatrix = np.cov(np.transpose(np.array(tableB_Scaled)))
tableC_covarianceMatrix = np.cov(np.transpose(np.array(tableC_Scaled)))

pca_tableA = pca4.fit(tableA_covarianceMatrix).transform(tableA_covarianceMatrix)
pca_tableB = pca4.fit(tableB_covarianceMatrix).transform(tableB_covarianceMatrix)
pca_tableC = pca4.fit(tableC_covarianceMatrix).transform(tableC_covarianceMatrix)

In [4]:
df_pca_tableA = pd.DataFrame(pca_tableA, columns=['PC1','PC2','PC3','PC4'])
df_pca_tableB = pd.DataFrame(pca_tableB, columns=['PC1','PC2','PC3','PC4'])
df_pca_tableC = pd.DataFrame(pca_tableC, columns=['PC1','PC2','PC3','PC4'])

# tableA_pca_vertically = df_pca_tableA['PC1'].append([df_pca_tableA['PC2'],df_pca_tableA['PC3'],df_pca_tableA['PC4']]).reset_index(drop=True)
# tableB_pca_vertically = df_pca_tableB['PC1'].append([df_pca_tableB['PC2'],df_pca_tableB['PC3'],df_pca_tableB['PC4']]).reset_index(drop=True)
# print('correlation of data of tableA and tableB is {}'.format(np.corrcoef(tableA_pca_vertically,tableB_pca_vertically)[0,1]))

In [5]:
print(pca_tableA)
print(pca_tableB)
print(pca_tableC)

[[-0.11824057  0.6968626  -0.20827297 -0.10040852]
 [-1.11250186  0.24214583  0.32144991 -0.00152888]
 [-1.2823905  -0.61509176 -0.18580633  0.05154817]
 [ 1.29486806 -0.55332438  0.08131748 -0.11560575]
 [ 1.21826487  0.22940771 -0.00868808  0.16599497]]
[[ 3.92502557e-01  8.69161147e-01 -4.94870754e-01  3.90965344e-01]
 [ 8.05030450e-02 -7.61831237e-01  4.12772411e-02 -3.87703350e-02]
 [-4.69007198e-01 -7.01942691e-01  3.15170142e-02  1.69150251e-01]
 [ 8.57575031e-01 -3.04477496e-01 -8.11688437e-02  1.58540751e-01]
 [-3.15962418e-02  6.05121698e-01  1.05629712e+00  1.25452617e-04]
 [ 1.12719791e+00 -2.09878849e-01 -1.38180235e-01 -1.88155176e-01]
 [-1.23650403e+00  5.53111776e-01 -3.18492824e-01 -2.84967337e-01]
 [-1.10633040e+00 -4.00619196e-02 -2.61970281e-01 -1.76933937e-01]
 [ 1.46238844e+00  2.11674784e-01 -1.61116697e-02 -2.26548660e-01]
 [-1.07672911e+00 -2.20877211e-01  1.81703237e-01  1.96593646e-01]]
[[ 0.16699663  0.3389703   0.89709811 -0.37636138]
 [ 0.62783805 -0.58250

In [6]:
# tableA_pca_vertically = tableA_pca['PC1'].append(tableA_pca['PC2'],tableA_pca['PC3'],tableA_pca['PC4']).reset_index(drop=True)
# tableB_pca_vertically = tableB_pca['PC1'].append(tableB_pca['PC2'],tableB_pca['PC3'],tableA_pca['PC4'],tableA_pca['PC5']).reset_index(drop=True)
# print('correlation of data of tableA and tableB is {}'.format(np.corrcoef(tableA_pca_vertically,tableB_pca_vertically)[0,1]))